# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Squashed initial migration — full final schema, no data operations.
#
# NOTE on the django_crm dependency: django_crm and django_getresponse are mutually
# dependent (crm's 0010 builds proxy models on this app's models and depends on the
# old 0001_initial name, remapped here via `replaces`). This squash must therefore
# depend on a crm migration that PRECEDES crm's 0010 — the FK target (django_crm.form)
# is created by crm's 0001_initial. makemigrations pointed at an autodetected crm leaf;
# fixed manually (see also the regional note below).
#
# Generated by Django 6.0.7 on 2026-07-12

import django.db.models.deletion
from django.db import migrations, models

import django_getresponse.models.contact


class Migration(migrations.Migration):
    initial = True

    replaces = [
        ("django_getresponse", "0001_initial"),
        ("django_getresponse", "0002_cartsync_ordersync_productsync_and_more"),
        ("django_getresponse", "0003_getresponseshop_external_language_and_more"),
        ("django_getresponse", "0004_alter_categorysync_unique_together_and_more"),
        ("django_getresponse", "0005_getresponseshop_marketing_consent_type_name"),
        ("django_getresponse", "0006_alter_getresponseshop_marketing_consent_type_name"),
        ("django_getresponse", "0007_getresponseshop_crm_campaign"),
        ("django_getresponse", "0008_getresponsecampaign_default_day_of_cycle"),
        ("django_getresponse", "0009_getresponseshop_domain_url_cart"),
    ]

    dependencies = [
        ("django_crm", "0001_initial"),
        ("django_pim", "0001_squashed_0060_productattribute_nulls_not_distinct"),
        # makemigrations points at the regional leaf (0002_reset_pk_sequences); the FK
        # targets are created by the regional squash — depending on the leaf would raise
        # InconsistentMigrationHistory on bases that predate 0002.
        ("django_regional", "0001_squashed_0006_country_default_currency"),
    ]

    operations = [
        migrations.CreateModel(
            name="Channel",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("idx", models.CharField(help_text="Unique identifier for the channel", max_length=255, unique=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="GetResponseAccount",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("api_key", models.CharField(help_text="GetResponse API key for authentication", max_length=64)),
                (
                    "is_enabled",
                    models.BooleanField(default=False, help_text="Enable/disable this GetResponse account globally"),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="Friendly name for this account (e.g., 'Production', 'Test')",
                        max_length=128,
                    ),
                ),
                (
                    "channel",
                    models.ForeignKey(
                        help_text="Channel this GetResponse account belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="getresponse_accounts",
                        to="django_getresponse.channel",
                    ),
                ),
            ],
            options={
                "verbose_name": "GetResponse Account",
                "verbose_name_plural": "GetResponse Accounts",
                "db_table": "django_getresponse_account",
                "unique_together": {("channel", "api_key")},
            },
        ),
        migrations.CreateModel(
            name="GetResponseCampaign",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(help_text="Campaign name from GetResponse", max_length=128)),
                ("campaign_id", models.CharField(help_text="Campaign ID from GetResponse API", max_length=64)),
                ("is_active", models.BooleanField(default=False, help_text="Enable/disable this campaign")),
                (
                    "default_day_of_cycle",
                    models.IntegerField(
                        blank=True,
                        help_text="Default day of the autoresponder cycle for contacts added to this campaign. Used when a contact does not set its own day_of_cycle; leave empty to omit dayOfCycle.",
                        null=True,
                    ),
                ),
                (
                    "account",
                    models.ForeignKey(
                        help_text="GetResponse account that owns this campaign",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="campaigns",
                        to="django_getresponse.getresponseaccount",
                    ),
                ),
                (
                    "language",
                    models.ForeignKey(
                        blank=True,
                        help_text="Language for this campaign. If empty, this campaign serves as a fallback for languages without a specific campaign.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="django_regional.language",
                    ),
                ),
            ],
            options={
                "verbose_name": "GetResponse Campaign",
                "verbose_name_plural": "GetResponse Campaigns",
                "db_table": "django_getresponse_campaign",
            },
        ),
        migrations.CreateModel(
            name="GetResponseContact",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("day_of_cycle", models.IntegerField(blank=True, help_text="Day of autoresponder cycle", null=True)),
                ("scoring", models.IntegerField(blank=True, help_text="Contact scoring value", null=True)),
                (
                    "tags",
                    models.JSONField(
                        default=django_getresponse.models.contact.get_default_tags,
                        help_text="Tags to assign to contact in GetResponse",
                    ),
                ),
                (
                    "custom_field_values",
                    models.JSONField(
                        default=django_getresponse.models.contact.get_default_custom_field_values,
                        help_text="Custom field values for the contact",
                    ),
                ),
                (
                    "contact_id",
                    models.CharField(
                        blank=True, help_text="GetResponse contact ID (returned from API)", max_length=255, null=True
                    ),
                ),
                (
                    "sync_status",
                    models.CharField(
                        choices=[("pending", "Pending"), ("synced", "Synced"), ("failed", "Failed")],
                        default="pending",
                        help_text="Synchronization status with GetResponse",
                        max_length=20,
                    ),
                ),
                (
                    "last_sync_at",
                    models.DateTimeField(blank=True, help_text="Last successful synchronization timestamp", null=True),
                ),
                ("error_message", models.TextField(blank=True, help_text="Last error message if sync failed")),
                (
                    "campaign",
                    models.ForeignKey(
                        help_text="GetResponse campaign for this contact",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contacts",
                        to="django_getresponse.getresponsecampaign",
                    ),
                ),
                (
                    "form",
                    models.ForeignKey(
                        help_text="CRM form associated with this contact",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="getresponse_contacts",
                        to="django_crm.form",
                    ),
                ),
            ],
            options={
                "verbose_name": "GetResponse Contact",
                "verbose_name_plural": "GetResponse Contacts",
                "db_table": "django_getresponse_contact",
            },
        ),
        migrations.CreateModel(
            name="GetResponseShop",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(help_text="Shop name in GetResponse (1-64 characters)", max_length=64)),
                (
                    "domain_url",
                    models.CharField(
                        blank=True,
                        help_text="Base domain URL for product links (e.g., 'https://shop.example.com')",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "domain_url_categories",
                    models.CharField(
                        blank=True,
                        help_text="Base domain URL for category links (e.g., 'https://shop.example.com')",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "domain_url_cart",
                    models.CharField(
                        blank=True,
                        help_text="Cart page URL sent to GetResponse as cartUrl (e.g., 'https://shop.example.com/cart')",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "customer_type_field_id",
                    models.CharField(
                        blank=True,
                        help_text="GetResponse custom field ID for customer_type (new/returning)",
                        max_length=128,
                        null=True,
                    ),
                ),
                (
                    "total_orders_count_field_id",
                    models.CharField(
                        blank=True,
                        help_text="GetResponse custom field ID for total_orders_count",
                        max_length=128,
                        null=True,
                    ),
                ),
                (
                    "last_order_date_field_id",
                    models.CharField(
                        blank=True,
                        help_text="GetResponse custom field ID for last_order_date",
                        max_length=128,
                        null=True,
                    ),
                ),
                (
                    "marketing_consent_type_name",
                    models.CharField(
                        blank=True,
                        default="marketing",
                        help_text="django_crm ConsentType.name that gates GR sync. Cart/Order push and GR contact creation happen only after this consent is granted (consent_bool=True). Leave EMPTY to disable the gate for this shop: cart/order then sync without any consent check (contact auto-created from the cart/order email).",
                        max_length=64,
                    ),
                ),
                (
                    "gr_shop_id",
                    models.CharField(
                        blank=True, help_text="GetResponse shop ID (assigned after sync)", max_length=128, null=True
                    ),
                ),
                (
                    "sync_status",
                    models.CharField(
                        choices=[("pending", "Pending"), ("synced", "Synced"), ("failed", "Failed")],
                        default="pending",
                        help_text="Synchronization status with GetResponse",
                        max_length=20,
                    ),
                ),
                (
                    "last_sync_at",
                    models.DateTimeField(blank=True, help_text="Last successful synchronization timestamp", null=True),
                ),
                ("error_message", models.TextField(blank=True, help_text="Last error message if sync failed")),
                (
                    "cart_campaign",
                    models.ForeignKey(
                        blank=True,
                        help_text="Campaign for cart/order contacts (if not set, will auto-select by language)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cart_shops",
                        to="django_getresponse.getresponsecampaign",
                    ),
                ),
                (
                    "channel",
                    models.ForeignKey(
                        help_text="Channel this shop belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="getresponse_shops",
                        to="django_getresponse.channel",
                    ),
                ),
                (
                    "crm_campaign",
                    models.ForeignKey(
                        blank=True,
                        help_text="Campaign for contacts created from the CRM newsletter form (if not set, auto-selects by language).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="crm_shops",
                        to="django_getresponse.getresponsecampaign",
                    ),
                ),
                (
                    "currency",
                    models.ForeignKey(
                        help_text="Shop currency (ISO 4217 code)",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="django_regional.currency",
                    ),
                ),
                (
                    "external_language",
                    models.ForeignKey(
                        help_text="Shop language sent to GetResponse API (ISO 639-1 code, e.g., 'en')",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="getresponse_shops_external",
                        to="django_regional.language",
                    ),
                ),
                (
                    "language",
                    models.ForeignKey(
                        help_text="Shop language for DB lookups (ISO 639-1 code, e.g., 'gb', 'us')",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="getresponse_shops",
                        to="django_regional.language",
                    ),
                ),
                (
                    "price_country",
                    models.ForeignKey(
                        blank=True,
                        help_text="Country for price calculation",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="django_regional.country",
                    ),
                ),
            ],
            options={
                "verbose_name": "GetResponse Shop",
                "verbose_name_plural": "GetResponse Shops",
                "db_table": "django_getresponse_shop",
            },
        ),
        migrations.CreateModel(
            name="CategorySync",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "gr_category_id",
                    models.CharField(blank=True, help_text="Category ID in GetResponse API", max_length=128, null=True),
                ),
                (
                    "gr_shop_id",
                    models.CharField(
                        blank=True,
                        help_text="Shop ID in GetResponse API (legacy - use shop FK instead)",
                        max_length=128,
                    ),
                ),
                (
                    "external_id",
                    models.CharField(
                        help_text="External ID sent to GetResponse (e.g., 'shop_cat_123')", max_length=255
                    ),
                ),
                (
                    "sync_status",
                    models.CharField(
                        choices=[("pending", "Pending"), ("synced", "Synced"), ("failed", "Failed")],
                        default="pending",
                        help_text="Current synchronization status",
                        max_length=20,
                    ),
                ),
                (
                    "last_sync_at",
                    models.DateTimeField(blank=True, help_text="Last successful synchronization timestamp", null=True),
                ),
                (
                    "last_request_data",
                    models.JSONField(
                        blank=True, default=dict, help_text="Last POST/PATCH request payload sent to GetResponse"
                    ),
                ),
                (
                    "last_response_data",
                    models.JSONField(blank=True, default=dict, help_text="Last response received from GetResponse API"),
                ),
                ("error_message", models.TextField(blank=True, help_text="Error message if sync_status is 'failed'")),
                ("sync_attempts", models.IntegerField(default=0, help_text="Number of synchronization attempts")),
                (
                    "product_category",
                    models.ForeignKey(
                        help_text="Product category from django_pim",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="getresponse_syncs",
                        to="django_pim.productcategory",
                    ),
                ),
                (
                    "channel",
                    models.ForeignKey(
                        help_text="GetResponse channel (shop.idx == channel.idx)",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="category_syncs",
                        to="django_getresponse.channel",
                    ),
                ),
                (
                    "shop",
                    models.ForeignKey(
                        help_text="GetResponse shop this category is synced to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="category_syncs",
                        to="django_getresponse.getresponseshop",
                    ),
                ),
            ],
            options={
                "verbose_name": "Category Sync",
                "verbose_name_plural": "Category Syncs",
                "db_table": "django_getresponse_category_sync",
            },
        ),
        migrations.CreateModel(
            name="CartSync",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("cart_id", models.CharField(help_text="Django checkout Cart UUID", max_length=255)),
                (
                    "gr_cart_id",
                    models.CharField(
                        blank=True, help_text="GetResponse cart ID (assigned after sync)", max_length=128, null=True
                    ),
                ),
                (
                    "contact_id",
                    models.CharField(help_text="GetResponse contact ID (required by GetResponse API)", max_length=255),
                ),
                (
                    "external_id",
                    models.CharField(help_text="External ID for cart (cart_id)", max_length=255, unique=True),
                ),
                ("total_price", models.DecimalField(decimal_places=2, help_text="Cart total price", max_digits=10)),
                ("currency", models.CharField(help_text="Currency code (ISO 4217)", max_length=3)),
                ("cart_url", models.CharField(help_text="URL to cart page", max_length=512)),
                ("selected_variants", models.JSONField(default=list, help_text="List of selected product variants")),
                (
                    "sync_status",
                    models.CharField(
                        choices=[("pending", "Pending"), ("synced", "Synced"), ("failed", "Failed")],
                        default="pending",
                        help_text="Synchronization status",
                        max_length=20,
                    ),
                ),
                (
                    "last_sync_at",
                    models.DateTimeField(blank=True, help_text="Last successful synchronization timestamp", null=True),
                ),
                ("last_request_data", models.JSONField(blank=True, help_text="Last API request payload", null=True)),
                ("last_response_data", models.JSONField(blank=True, help_text="Last API response data", null=True)),
                ("error_message", models.TextField(blank=True, help_text="Last error message if sync failed")),
                ("sync_attempts", models.IntegerField(default=0, help_text="Number of sync attempts")),
                (
                    "shop",
                    models.ForeignKey(
                        help_text="GetResponse shop for this cart",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cart_syncs",
                        to="django_getresponse.getresponseshop",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cart Sync",
                "verbose_name_plural": "Cart Syncs",
                "db_table": "django_getresponse_cart_sync",
            },
        ),
        migrations.CreateModel(
            name="OrderSync",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("order_id", models.CharField(help_text="Django checkout Order UUID", max_length=255)),
                (
                    "gr_order_id",
                    models.CharField(
                        blank=True, help_text="GetResponse order ID (assigned after sync)", max_length=128, null=True
                    ),
                ),
                ("contact_id", models.CharField(help_text="GetResponse contact ID", max_length=255)),
                (
                    "external_id",
                    models.CharField(help_text="External ID for order (order_id)", max_length=255, unique=True),
                ),
                ("total_price", models.DecimalField(decimal_places=2, help_text="Order total price", max_digits=10)),
                ("currency", models.CharField(help_text="Currency code (ISO 4217)", max_length=3)),
                (
                    "status",
                    models.CharField(help_text="GetResponse order status (PENDING, COMPLETED, etc.)", max_length=50),
                ),
                ("processed_at", models.DateTimeField(help_text="Order processing timestamp")),
                ("selected_variants", models.JSONField(default=list, help_text="List of ordered product variants")),
                ("billing_address", models.JSONField(blank=True, default=dict, help_text="Billing address data")),
                ("shipping_address", models.JSONField(blank=True, default=dict, help_text="Shipping address data")),
                (
                    "sync_status",
                    models.CharField(
                        choices=[("pending", "Pending"), ("synced", "Synced"), ("failed", "Failed")],
                        default="pending",
                        help_text="Synchronization status",
                        max_length=20,
                    ),
                ),
                (
                    "last_sync_at",
                    models.DateTimeField(blank=True, help_text="Last successful synchronization timestamp", null=True),
                ),
                ("last_request_data", models.JSONField(blank=True, help_text="Last API request payload", null=True)),
                ("last_response_data", models.JSONField(blank=True, help_text="Last API response data", null=True)),
                ("error_message", models.TextField(blank=True, help_text="Last error message if sync failed")),
                ("sync_attempts", models.IntegerField(default=0, help_text="Number of sync attempts")),
                (
                    "shop",
                    models.ForeignKey(
                        help_text="GetResponse shop for this order",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="order_syncs",
                        to="django_getresponse.getresponseshop",
                    ),
                ),
            ],
            options={
                "verbose_name": "Order Sync",
                "verbose_name_plural": "Order Syncs",
                "db_table": "django_getresponse_order_sync",
            },
        ),
        migrations.CreateModel(
            name="ProductSync",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "gr_product_id",
                    models.CharField(blank=True, help_text="Product ID in GetResponse API", max_length=128, null=True),
                ),
                ("external_id", models.CharField(help_text="External ID sent to GetResponse", max_length=255)),
                (
                    "sync_status",
                    models.CharField(
                        choices=[("pending", "Pending"), ("synced", "Synced"), ("failed", "Failed")],
                        default="pending",
                        help_text="Current synchronization status",
                        max_length=20,
                    ),
                ),
                (
                    "last_sync_at",
                    models.DateTimeField(blank=True, help_text="Last successful synchronization timestamp", null=True),
                ),
                (
                    "last_request_data",
                    models.JSONField(blank=True, default=dict, help_text="Last request payload sent to GetResponse"),
                ),
                (
                    "last_response_data",
                    models.JSONField(blank=True, default=dict, help_text="Last response received from GetResponse API"),
                ),
                ("error_message", models.TextField(blank=True, help_text="Error message if sync_status is 'failed'")),
                ("sync_attempts", models.IntegerField(default=0, help_text="Number of synchronization attempts")),
                (
                    "product",
                    models.ForeignKey(
                        help_text="Product from django_pim",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="getresponse_syncs",
                        to="django_pim.product",
                    ),
                ),
                (
                    "shop",
                    models.ForeignKey(
                        help_text="GetResponse shop",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_syncs",
                        to="django_getresponse.getresponseshop",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product Sync",
                "verbose_name_plural": "Product Syncs",
                "db_table": "django_getresponse_product_sync",
            },
        ),
        migrations.AddIndex(
            model_name="getresponsecampaign",
            index=models.Index(fields=["account", "is_active"], name="django_getr_account_0071ce_idx"),
        ),
        migrations.AddIndex(
            model_name="getresponsecampaign",
            index=models.Index(fields=["language", "is_active"], name="django_getr_languag_0c29ee_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="getresponsecampaign",
            unique_together={("account", "campaign_id")},
        ),
        migrations.AddIndex(
            model_name="getresponsecontact",
            index=models.Index(fields=["campaign", "form"], name="django_getr_campaig_e1bc53_idx"),
        ),
        migrations.AddIndex(
            model_name="getresponsecontact",
            index=models.Index(fields=["contact_id"], name="django_getr_contact_e95eee_idx"),
        ),
        migrations.AddIndex(
            model_name="getresponsecontact",
            index=models.Index(fields=["sync_status"], name="django_getr_sync_st_395e26_idx"),
        ),
        migrations.AddIndex(
            model_name="getresponseshop",
            index=models.Index(fields=["channel", "sync_status"], name="django_getr_channel_cc21bc_idx"),
        ),
        migrations.AddIndex(
            model_name="getresponseshop",
            index=models.Index(fields=["gr_shop_id"], name="django_getr_gr_shop_b1fd79_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="getresponseshop",
            unique_together={("channel", "name")},
        ),
        migrations.AddIndex(
            model_name="categorysync",
            index=models.Index(fields=["shop", "sync_status"], name="django_getr_shop_id_bf1c5e_idx"),
        ),
        migrations.AddIndex(
            model_name="categorysync",
            index=models.Index(fields=["channel", "sync_status"], name="django_getr_channel_ee21db_idx"),
        ),
        migrations.AddIndex(
            model_name="categorysync",
            index=models.Index(fields=["gr_category_id"], name="django_getr_gr_cate_a0c44a_idx"),
        ),
        migrations.AddIndex(
            model_name="categorysync",
            index=models.Index(fields=["external_id"], name="django_getr_externa_b9b65c_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="categorysync",
            unique_together={("shop", "product_category")},
        ),
        migrations.AddIndex(
            model_name="cartsync",
            index=models.Index(fields=["cart_id"], name="django_getr_cart_id_fa43bc_idx"),
        ),
        migrations.AddIndex(
            model_name="cartsync",
            index=models.Index(fields=["gr_cart_id"], name="django_getr_gr_cart_ef8c6f_idx"),
        ),
        migrations.AddIndex(
            model_name="cartsync",
            index=models.Index(fields=["sync_status"], name="django_getr_sync_st_723e2b_idx"),
        ),
        migrations.AddIndex(
            model_name="cartsync",
            index=models.Index(fields=["contact_id"], name="django_getr_contact_44d755_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="cartsync",
            unique_together={("shop", "cart_id")},
        ),
        migrations.AddIndex(
            model_name="ordersync",
            index=models.Index(fields=["order_id"], name="django_getr_order_i_26a886_idx"),
        ),
        migrations.AddIndex(
            model_name="ordersync",
            index=models.Index(fields=["gr_order_id"], name="django_getr_gr_orde_e57ee0_idx"),
        ),
        migrations.AddIndex(
            model_name="ordersync",
            index=models.Index(fields=["sync_status"], name="django_getr_sync_st_c6343a_idx"),
        ),
        migrations.AddIndex(
            model_name="ordersync",
            index=models.Index(fields=["contact_id"], name="django_getr_contact_43549a_idx"),
        ),
        migrations.AddIndex(
            model_name="ordersync",
            index=models.Index(fields=["status"], name="django_getr_status_91d616_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="ordersync",
            unique_together={("shop", "order_id")},
        ),
        migrations.AddIndex(
            model_name="productsync",
            index=models.Index(fields=["shop", "sync_status"], name="django_getr_shop_id_9867bb_idx"),
        ),
        migrations.AddIndex(
            model_name="productsync",
            index=models.Index(fields=["gr_product_id"], name="django_getr_gr_prod_3a9eeb_idx"),
        ),
        migrations.AddIndex(
            model_name="productsync",
            index=models.Index(fields=["external_id"], name="django_getr_externa_d43e17_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="productsync",
            unique_together={("shop", "product")},
        ),
    ]
